"""Add images

Revision ID: 7344d50630dc
Revises: 515f7f17d126
Create Date: 2022-01-17 12:38:29.463082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7344d50630dc'
down_revision = '515f7f17d126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('actors', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('actors', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('directors', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('directors', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.add_column('movies', sa.Column('cover_id', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('banner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movies', 'images', ['banner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'movies', 'images', ['cover_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'banner_id')
    op.drop_column('movies', 'cover_id')
    op.alter_column('directors', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('directors', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('actors', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('actors', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('images')
    # ### end Alembic commands ###
